all:
	$(CC) -o simple_video simple_video.c `sdl-config --cflags --libs` -s
	$(CC) -o simple_video2 simple_video2.c `sdl-config --cflags --libs` -s
	$(CC) -o simple_video3 simple_video3.c `sdl-config --cflags --libs` -s
